src/main/java/it/smartphonecombo/uecapabilityparser/Utility.kt
Oops, IntelliJ also did some formatting. If it matters, I can remove it.
=> feat: implement more helpful error message for invalid 0xB826 hexdumps

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
- Update kotlin to 1.8.10
- Update gradle to 8.0
- Update grallvm native plugin to 0.9.20
- Update junit jupiter to 5.9.2
- Update slf4j-nop to 2.0.6
- Update mts-asn1 to [7784a9f](https://github.com/HandyMenny/mts-asn1/commit/7784a9fc56cc26f585fc05f9d9c080f6a425143e)
=> Dependencies update

.github/workflows/pre-release.yaml, .github/workflows/release.yaml, Dockerfile, build.gradle.kts, src/main/dist/uecapabilityparser, src/main/dist/uecapabilityparser.bat
- Enable application plugin
- Customize distribution zip
- Set target JDK to jdk11
- Update dockerfile/workflows to use gradle build with jdk11 
- Enable gradle cache for workflows
- Cleanup gradle.kts
=> Use gradle build with application plugin

build.gradle.kts
codeql doesn't support 1.8.10 yet
=> downgrade kotlin to 1.8.0

.github/workflows/docker.yaml, .github/workflows/pre-release.yaml, .github/workflows/release.yaml
- build docker image only when new tag is pushed
- include zip archive in releases
- publish nightly every 24h if there're new commits
=> Workflows updates

.github/workflows/pre-release.yaml, .github/workflows/test.yaml
- pass codecov token to codecov-action
- update pre-release schedule
=> Workflow updates

.github/workflows/test.yaml
check task also run style checks in addition to unit tests
=> workflow: use check task

src/main/java/it/smartphonecombo/uecapabilityparser/importer/ltenr/ImportCapabilityInformationJson.kt
- set "default" 100MHz even if no bw is reported for 30kHz
- fix FR2 DL modulation
- sort nr bands
=> Improve UeCapabilityInformation parser

src/main/java/it/smartphonecombo/uecapabilityparser/MainCli.kt
leftovers of "drop compacted capabilities" in 19318bd
=> mainCli: remove dead code

src/test/java/it/smartphonecombo/uecapabilityparser/MainCliTest.kt
- reset configs before each test
- don't redirect stderr
=> Improve reliability of cli tests

build.gradle.kts
Main change:
ConverterQcat: fix parsing of some sequenceOf arrays
Full changelog: https://github.com/HandyMenny/mts-asn1/compare/1125e38...b83205d
=> gradle: update mtsAsn1Version

README.md
=> readme: add basic build/run instructions

build.gradle.kts
This reverts commit ce02811eec427a2a67dac65651ca101967a8c62a.
=> Revert "coverage: exclude LERandomAccessFile from code coverage"

.github/workflows/test.yaml, build.gradle.kts
jacoco doesn't support inline functions
=> switch to kover for code coverage report

src/main/java/it/smartphonecombo/uecapabilityparser/extension/Int.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/Import0xB0CD.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/Import0xB826.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportCapabilityInformation.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportLteCarrierPolicy.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportMTKLte.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportNrCapPrune.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportNvItem.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/BwClass.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/IComponent.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/lte/ComboLte.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/lte/ComponentLte.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/nr/ComboNr.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/nr/ComponentNr.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/Utility.kt, src/test/java/it/smartphonecombo/uecapabilityparser/importer/ImportCapabilityInformationTest.kt
It's an inline class backed by char, so the runtime overhead should be minimal
=> add BwClass class

build.gradle.kts
fix https://github.com/HandyMenny/mts-asn1/issues/26
=> Update mts asn1 version

src/main/java/it/smartphonecombo/uecapabilityparser/model/modulation/Modulation.kt
This is the recommended way since kotlin 1.9
=> replace Enum.values() with Enum.entries

build.gradle.kts
jna dependency is required by mordant used by clickt
=> shadow: minimize: keep jna dependency

gradle.properties
Doesn't work well with spotless plugin
=> Disable gradle config cache

src/main/java/it/smartphonecombo/uecapabilityparser/cli/Clikt.kt, src/main/java/it/smartphonecombo/uecapabilityparser/server/JavalinApp.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/ImportQcHelpers.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/Parsing.kt, src/test/java/it/smartphonecombo/uecapabilityparser/cli/CliJsonOutputTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/cli/MainTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeParseTest.kt
Also deprecate --multiple0xB826 option
=> Make multiple0xB826 the default behaviour

src/main/java/it/smartphonecombo/uecapabilityparser/model/combo/ComboEnDc.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/combo/ComboNr.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/combo/ComboNrDc.kt
Fixup commit 2613a33625b9c6992664be5c62d242064ac70c46
=> Set featureset as transient (again)

src/main/java/it/smartphonecombo/uecapabilityparser/cli/Clikt.kt, src/main/java/it/smartphonecombo/uecapabilityparser/cli/HelpMessage.kt, src/main/java/it/smartphonecombo/uecapabilityparser/server/ServerMode.kt
If port is 0 a random port is used
=> Document port 0 behaviour and set it as default

build.gradle.kts
=> update mts-asn-1 to 24f52fc

src/main/java/it/smartphonecombo/uecapabilityparser/server/JavalinApp.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeCompressionTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeCsvTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeOthersTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeParseTest.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeStoreTest.kt
Versioned endpoints are deprecated
=> Add Endpoints without version

build.gradle.kts, src/main/java/it/smartphonecombo/uecapabilityparser/server/JavalinApp.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/Parsing.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeReparseTest.kt
Parallelism limited to 2 to limit ram usage
=> Make reparse async

Dockerfile, src/main/java/it/smartphonecombo/uecapabilityparser/cli/Clikt.kt, src/main/java/it/smartphonecombo/uecapabilityparser/cli/HelpMessage.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/multi/ImportPcap.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/multi/ImportScat.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/scat/ScatLogType.kt, src/main/java/it/smartphonecombo/uecapabilityparser/server/JavalinApp.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/MultiParsing.kt
=> SCAT integration

src/main/java/it/smartphonecombo/uecapabilityparser/extension/File.kt, src/main/java/it/smartphonecombo/uecapabilityparser/extension/InputStream.kt, src/main/java/it/smartphonecombo/uecapabilityparser/importer/multi/ImportScat.kt
- fix sdm support
- properly cleanup temp resources
=> Improve ImportScat

src/main/java/it/smartphonecombo/uecapabilityparser/cli/Clikt.kt, src/main/java/it/smartphonecombo/uecapabilityparser/cli/HelpMessage.kt, src/main/java/it/smartphonecombo/uecapabilityparser/server/JavalinApp.kt, src/test/java/it/smartphonecombo/uecapabilityparser/server/ServerModeOthersTest.kt, src/test/resources/server/inputForOthers/custom.css, src/test/resources/server/inputForOthers/custom.js
These options respectively inject a custom css file or a custom js file in the web UI
=> Server: add custom-css and custom-js options

.github/workflows/dependencies.yaml
=> Revert #394 #395

Dockerfile
scat 1.3.0 depends on native libraries
=> docker: move scat installation to deploy stage

src/main/java/it/smartphonecombo/uecapabilityparser/cli/HelpMessage.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/Intern.kt, src/main/java/it/smartphonecombo/uecapabilityparser/util/Optimization.kt
This optimization saves memory up to 90% for 5k capabilities or 60% for 1k capabilities
=> Optimize space occupied by cache

build.gradle.kts
Mordant-jvm-jna-jvm is required by clikt
=> always include mordant-jvm-jna-jvm in shadow jar

src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportShannonNrUeCap.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/shannon/nr/ShannonComponentNr.kt, src/main/java/it/smartphonecombo/uecapabilityparser/model/shannon/nr/ShannonNrUECap.kt, src/main/resources/definition/ShannonNrUeCap.proto, src/test/java/it/smartphonecombo/uecapabilityparser/model/ShannonNrUECapTest.kt
=> Rename ShannonUECapNr to ShannonNrUECap

src/main/java/it/smartphonecombo/uecapabilityparser/importer/ImportCapabilityInformation.kt, src/test/java/it/smartphonecombo/uecapabilityparser/importer/ImportCapabilityInformationTest.kt, src/test/resources/capabilityInformation/input/ueCapNrDc1024qam.json, src/test/resources/capabilityInformation/oracle/ueCapNrDc1024qam.json
Note that pdsch-1024QAM-2MIMO-FR1-r17 is not supported
=> importcapabilityinformation: support pdsch-1024QAM-FR1-r17
